### ISSUE TITLE
problem with query on query_requests.go

### ISSUE THREAD

**Issue by mcocera** [zwennesm/vertica-prometheus-exporter#3]
I found an error when execute the query inside the query_requests.go . If the result on the query is null, the container drops an error and crash the application. For resolve it i changed the query on the file and i added on the select clause the COALESCE for, when the result is null, the value it's converted on 0 and not drop the error. 
SELECT
                user_name,
                SUM(**COALESCE**(request_duration_ms,0))::INT request_duration_ms,
                SUM(**COALESCE**(memory_acquired_mb,0))::INT memory_acquired_mb
I tested on my environment and works fine. 
For information and if like to correct.

**Comment by ghost** [comment]
Thanks for taking the time opening an issue and finding a solution @mcocera. I appreciate it! I merged the changed you mentioned to master and updated the binaries/docker image.
