### ISSUE TITLE
ParameterStatus warnings for each query run each iteration

### ISSUE THREAD

**Issue by verticacrossman** [zwennesm/vertica-prometheus-exporter#4]
Hi,
I'm running 0.4 against Vertica 9.3 and 10.0 on same host as the exporter and different host than the exporter. I've tried the binary and doing a build but see the issue below in both. I've tried with and without Prometheus running and see it either way.

I start the exporter and I get the INFO line and it sits quietly. Then I go into my http://host:8080/metrics page. As soon as I open the page the exporter output the WARNings below, 3 warnings for each of the 5 queries. If I do a refresh on the http page I will get them again. If Prometheus is running then I see them each time the interval is reached.

[dbadmin@localhost ~]$ ./vertica-prometheus-exporter -db_name VMart -db_user dbadmin -db_password vert1caBdp -db_host 172.16.116.21
INFO[0000] starting serving metrics at 0.0.0.0:8080/metrics
Aug 12 12:17:14.732163 WARN connection: unhandled message: ParameterStatus: standard_conforming_strings='on'
Aug 12 12:17:14.732233 WARN connection: unhandled message: ParameterStatus: MARS='off'
Aug 12 12:17:14.732252 WARN connection: unhandled message: ParameterStatus: client_locale='en_US@collation=binary'
Aug 12 12:17:21.298004 WARN connection: unhandled message: ParameterStatus: standard_conforming_strings='on'
Aug 12 12:17:21.298051 WARN connection: unhandled message: ParameterStatus: MARS='off'
Aug 12 12:17:21.298070 WARN connection: unhandled message: ParameterStatus: client_locale='en_US@collation=binary'
Aug 12 12:17:21.399071 WARN connection: unhandled message: ParameterStatus: standard_conforming_strings='on'
Aug 12 12:17:21.399103 WARN connection: unhandled message: ParameterStatus: MARS='off'
Aug 12 12:17:21.399122 WARN connection: unhandled message: ParameterStatus: client_locale='en_US@collation=binary'
# here I refreshed the http page
Aug 12 12:18:51.199639 WARN connection: unhandled message: ParameterStatus: standard_conforming_strings='on'
Aug 12 12:18:51.199683 WARN connection: unhandled message: ParameterStatus: MARS='off'
Aug 12 12:18:51.199704 WARN connection: unhandled message: ParameterStatus: client_locale='en_US@collation=binary'
Aug 12 12:18:57.459825 WARN connection: unhandled message: ParameterStatus: standard_conforming_strings='on'
Aug 12 12:18:57.459873 WARN connection: unhandled message: ParameterStatus: MARS='off'
Aug 12 12:18:57.459892 WARN connection: unhandled message: ParameterStatus: client_locale='en_US@collation=binary'
Aug 12 12:18:57.564423 WARN connection: unhandled message: ParameterStatus: standard_conforming_strings='on'
Aug 12 12:18:57.564458 WARN connection: unhandled message: ParameterStatus: MARS='off'
Aug 12 12:18:57.564477 WARN connection: unhandled message: ParameterStatus: client_locale='en_US@collation=binary'

So far I haven't been able to debug why these appear. The client_locale and standard_conforming_strings are both normal configuration parameters set in the database. The MARS one is supposed to only be valid for JDBC and doesn't show up in traces of the connection. I do not see these with any other client apps using other Vertica drivers (e.g. ODBC, JDBC, Python).

If I run the exporter in background using & these still show up in the console. If I run it in the background with nohup and & then they do not appear but some others leak through to the console, e.g.
[dbadmin@localhost ~]$ level=info ts=2020-08-12T21:00:33.589Z caller=compact.go:495 component=tsdb msg="write block" mint=1597255200000 maxt=1597262400000 ulid=01EFJ7JYVPBD1R7M475VF27Z5D duration=62.384483ms
level=info ts=2020-08-12T21:00:33.598Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=2.366218ms
level=info ts=2020-08-12T21:00:33.648Z caller=compact.go:441 component=tsdb msg="compact blocks" count=3 mint=1597233600000 maxt=1597255200000 ulid=01EFJ7JYY6DAAG0H965P1X0FXZ sources="[01EFHK0PWXR8332HRP0T4FPFM9 01EFHVSKVNP2PXK5QTVB5TFN0K 01EFJ0Q7ATTWSFRZFPPNBFEWPH]" duration=42.259516ms

Stumped. Can provide whatever details you might need.

**Comment by verticacrossman** [comment]
I was able to resolve. This was actually an issue on the older vertica-sql-go driver you were using. All I had to do was run this command to update the package (which updated the driver from v0.2 to 1.10) and rebuild:
$ go get -u github.com/vertica/vertica-sql-go

**Comment by ghost** [comment]
@verticacrossman Apologies for the late response. I was on a holiday 🌞 . Thanks for taking the time for adding an issue and adding a fix! I will update the package and build a new version. Thanks again
